interface CatInfo {
  korName: string;
  engName: string;
}

export const CAT_MAPPINGS: Record<string, CatInfo> = {
  // Hidden
  SSAFY: { korName: '싸피냥', engName: 'SSAFY' },
  NewYearLuckCat: { korName: '새해복냥', engName: 'NewYearLuckCat' },
  MVPCat: { korName: 'MVP냥', engName: 'MVPCat' },
  IdeaCat: { korName: '아이디어냥', engName: 'IdeaCat' },
  CupidCat: { korName: '큐피드냥', engName: 'CupidCat' },
  ChocoFondueCat: { korName: '초코퐁듀냥', engName: 'ChocoFondueCat' },
  LikeCat: { korName: '좋아하냥', engName: 'LikeCat' },

  // S 등급
  CodingCat: { korName: '코딩냥', engName: 'CodingCat' },
  FishbowlCat: { korName: '어항냥', engName: 'FishbowlCat' },
  UFOCat: { korName: 'UFO냥', engName: 'UFOCat' },
  MagpieCat: { korName: '까치냥', engName: 'MagpieCat' },
  TteokgukCat: { korName: '떡국냥', engName: 'TteokgukCat' },
  CaffeineCat: { korName: '카페인냥', engName: 'CaffeineCat' },
  SingingCat: { korName: '노래냥', engName: 'SingingCat' },
  WorkCat: { korName: '출근냥', engName: 'WorkCat' },
  DiverCat: { korName: '다이버냥', engName: 'DiverCat' },
  AngryCat: { korName: '화났냥', engName: 'AngryCat' },

  // A 등급
  EatingCat: { korName: '밥먹냥', engName: 'EatingCat' },
  FlexCat: { korName: 'FLEX냥', engName: 'FlexCat' },
  BoxCat: { korName: '박스냥', engName: 'BoxCat' },
  FishingCat: { korName: '낚이냥', engName: 'FishingCat' },
  ToyCat: { korName: '장난감냥', engName: 'ToyCat' },
  LoafCat: { korName: '식빵냥', engName: 'LoafCat' },
  ColdCat: { korName: '추워냥', engName: 'ColdCat' },
  InvisibleCat: { korName: '안보이냥', engName: 'InvisibleCat' },
  AnonymousCat: { korName: 'Anonymous냥', engName: 'AnonymousCat' },
  YarnBallCat: { korName: '실타래냥', engName: 'YarnBallCat' },
  ComfortableCat: { korName: '편안하냥', engName: 'ComfortableCat' },
  SplashCat: { korName: '첨벙냥', engName: 'SplashCat' },
  FarmerCat: { korName: '농사냥', engName: 'FarmerCat' },
  BookCat: { korName: '독서냥', engName: 'BookCat' },
  PhoneCat: { korName: '폰하냥', engName: 'PhoneCat' },
  BirthdayCat: { korName: '생일냥', engName: 'BirthdayCat' },
  JumpCat: { korName: '점프냥', engName: 'JumpCat' },
  SickCat: { korName: '아프냥', engName: 'SickCat' },
  GymCat: { korName: '헬스냥', engName: 'GymCat' },

  // B 등급
  SpringCat: { korName: '스프링냥', engName: 'SpringCat' },
  PythonCat: { korName: '파이썬냥', engName: 'PythonCat' },
  TSCat: { korName: 'TS냥', engName: 'TSCat' },
  CSharpCat: { korName: 'C#냥', engName: 'CSharpCat' },
  CCat: { korName: 'C냥', engName: 'CCat' },
  CPlusPlusCat: { korName: 'C++냥', engName: 'CPlusPlusCat' },
  JavaCat: { korName: '자바냥', engName: 'JavaCat' },
  CSSCat: { korName: 'CSS냥', engName: 'CSSCat' },
  JSCat: { korName: 'JS냥', engName: 'JSCat' },
  HTMLCat: { korName: 'HTML냥', engName: 'HTMLCat' },
  ReactCat: { korName: '리액트냥', engName: 'ReactCat' },
  NodeCat: { korName: '노드냥', engName: 'NodeCat' },
  DjangoCat: { korName: '장고냥', engName: 'DjangoCat' },
  KotlinCat: { korName: '코틀린냥', engName: 'KotlinCat' },
  SwiftCat: { korName: '스위프트냥', engName: 'SwiftCat' },
  VueCat: { korName: '뷰냥', engName: 'VueCat' },
  RustCat: { korName: '러스트냥', engName: 'RustCat' },

  // C 등급
  Pumpkin: { korName: '호박', engName: 'Pumpkin' },
  Nero: { korName: '네로', engName: 'Nero' },
  Graybao: { korName: '회바오', engName: 'Graybao' },
  Pubao: { korName: '푸바오', engName: 'Pubao' },
  Ninja: { korName: '닌자', engName: 'Ninja' },
  Navy: { korName: '네이비', engName: 'Navy' },
  Apricot: { korName: '살구', engName: 'Apricot' },
  Lemon: { korName: '레몬', engName: 'Lemon' },
  Siam: { korName: '시루', engName: 'Siam' },
  Cheese: { korName: '치즈', engName: 'Cheese' },
  Barcode: { korName: '바코드', engName: 'Barcode' },
  Vanilla: { korName: '바닐라', engName: 'Vanilla' },
  Fox: { korName: '여우', engName: 'Fox' },
  Husky: { korName: '허스키', engName: 'Husky' },
  Raccoon: { korName: '너굴', engName: 'Raccoon' },
  Night: { korName: '밤', engName: 'Night' },
  Calico: { korName: '삼색이', engName: 'Calico' },
  DarkCloud: { korName: '먹구름', engName: 'DarkCloud' },
  Gray: { korName: '그레이', engName: 'Gray' },
  Banana: { korName: '바나나', engName: 'Banana' },
  Oreo: { korName: '오레오', engName: 'Oreo' },
  Penguin: { korName: '펭귄', engName: 'Penguin' },
  Grass: { korName: '잔디', engName: 'Grass' },
  Cloud: { korName: '구름', engName: 'Cloud' },
  Cherry: { korName: '체리', engName: 'Cherry' },
  Skunk: { korName: '스컹크', engName: 'Skunk' },
  Mackerel: { korName: '고등어', engName: 'Mackerel' },
  Tiger: { korName: '호랑', engName: 'Tiger' },
  Blackie: { korName: '까망', engName: 'Blackie' },
  Choco: { korName: '초코', engName: 'Choco' },
  Cream: { korName: '크림', engName: 'Cream' },

  // D 등급
  SquashedCat: { korName: '찌글냥', engName: 'SquashedCat' },
  WhirlwindCat: { korName: '회오리냥', engName: 'WhirlwindCat' },
  MeltingCat: { korName: '멜팅냥', engName: 'MeltingCat' },
  SlimeCat: { korName: '슬라임냥', engName: 'SlimeCat' },
  MeltingSlimeCat: { korName: '멜팅슬라임냥', engName: 'MeltingSlimeCat' },
  SleepyCat: { korName: '졸리냥', engName: 'SleepyCat' },
  JumpingCat: { korName: '폴짝냥', engName: 'JumpingCat' },
  TailZapCat: { korName: '꼬리찌릿냥', engName: 'TailZapCat' },
  SprawledCat: { korName: '널부렁냥', engName: 'SprawledCat' },
  ErrorCat: { korName: '에러냥', engName: 'ErrorCat' },
  NeckPillowCat: { korName: '목베개냥', engName: 'NeckPillowCat' },
  HillCat: { korName: '언덕냥', engName: 'HillCat' },
  QuestionCat: { korName: '뭐냥?', engName: 'QuestionCat' },
  ExclamationCat: { korName: '뭐냥!', engName: 'ExclamationCat' },
  HissingCat: { korName: '하악냥', engName: 'HissingCat' },
  ButtCat: { korName: '엉덩냥', engName: 'ButtCat' },
  RollingOverCat: { korName: '벌러덩냥', engName: 'RollingOverCat' },
  GroomingCat: { korName: '그루밍냥', engName: 'GroomingCat' },
  CrouchedCat: { korName: '쭈굴냥', engName: 'CrouchedCat' },
  FlippedCat: { korName: '뒤집냥', engName: 'FlippedCat' },
};
